import { style } from 'typestyle';
import { colors } from '../../styles/colors';

const styles = {
    container: style({
        padding: '8px',
    }),
    subContainerLight: style({
        height: '32px',
        display: 'flex',
        flexDirection: 'row',
        backgroundColor: colors.backgroundLight,
        border: '1px solid ',
        borderColor: colors.cardBorderLight,
        borderRadius: '4px',
        justifyContent: 'end',
    }),
    subContainerDark: style({
        height: '32px',
        display: 'flex',
        flexDirection: 'row',
        backgroundColor: colors.backgroundDark,
        border: '1px solid ',
        borderColor: colors.cardBorderDark,
        borderRadius: '4px',
        justifyContent: 'end',
    }),
    minusButton: style({
        color: colors.green_dark,
        backgroundColor: 'inherit',
        fontWeight: '900',
        width: '32px',
        border: '1px solid',
        borderColor: colors.green,
        borderTopLeftRadius: '4px',
        borderBottomLeftRadius: '4px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        cursor: 'pointer',
        $nest: {
            '&:disabled': {
                borderColor: colors.cardBorder,
                color: colors.cardBorder,
                opacity: '0.5',
                cursor: 'not-allowed',
            }
        },
    }),
    valueLight: style({
        border: '1px solid',
        borderColor: colors.green,
        color: colors.text,
        backgroundColor: 'inherit',
        minWidth: '32px',
        width: 'fit-content',
        padding: '0px 8px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontWeight: '500',
        fontSize: '16px',
        lineHeight: '0px',
        cursor: 'default',
        userSelect: 'none',
    }),
    valueDark: style({
        border: '1px solid',
        borderColor: colors.green,
        color: colors.textLight,
        backgroundColor: 'inherit',
        minWidth: '32px',
        width: 'fit-content',
        padding: '0px 8px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        fontWeight: '500',
        fontSize: '16px',
        lineHeight: '0px',
        cursor: 'default',
        userSelect: 'none',
    }),
    plusButton: style({
        color: colors.green_dark,
        backgroundColor: 'inherit',
        fontWeight: '900',
        width: '32px',
        border: '1px solid',
        borderColor: colors.green,
        borderTopRightRadius: '4px',
        borderBottomRightRadius: '4px',
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        cursor: 'pointer',
        $nest: {
            '&:disabled': {
                borderColor: colors.cardBorder,
                color: colors.cardBorder,
                opacity: '0.5',
                cursor: 'not-allowed',
            }
        },
    }),
};

export default styles;